# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86c695b51db8d30a60410a0d44aa7050779849e758e6a13206edead8e22096440b81fb1c87c69e844292709b695cf28399df4ee50550642bb38b2de8d3869697

test:
  secret_key_base: 120e4c30777f71ece5290df07a3677f8e93aa7f7edd114666d76792bbc0bfecffd090dc087ab4bc0cf864432c6d698e6d07190dabbf89bbf0a31e131ad3c4186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
